###############################################
# PR2 calibration values
###############################################

## right arm (excluding Shadow Hand)
r_shoulder_pan_calib_ref: -0.74550427
r_shoulder_lift_calib_ref: 0.02804656
r_upper_arm_roll_calib_ref: -1.5587278
r_elbow_flex_calib_ref: -1.15635323
r_forearm_roll_calib_ref: 0.0015972

## left arm
l_shoulder_pan_calib_ref: 0.82922099
l_shoulder_lift_calib_ref: 0.00735955
l_upper_arm_roll_calib_ref: 1.6052983
l_elbow_flex_calib_ref: -1.3054428
l_forearm_roll_calib_ref: 0.009442
l_wrist_flex_calib_ref: -0.5260045
l_wrist_roll_calib_ref: -1.53524592

## head joints
head_pan_calib_ref: 0.0303234
head_tilt_calib_ref: 0.0110223

## laser
laser_calib_ref: 0.0

## torso joints
torso_calib_ref: 0.00475

## azure offset
azure_kinect_camera_base_pos_x: 0.003692
azure_kinect_camera_base_pos_y: -0.003571
azure_kinect_camera_base_pos_z: 0.006248

azure_kinect_camera_base_rot_r: 0.003701
azure_kinect_camera_base_rot_p: -0.025780
azure_kinect_camera_base_rot_y: -0.001452
